@startuml
class user {
    integer id
}
class relationship {
    integer id
    integer followed_id
    integer follower_id
}

user --* relationship :relationshipを消す follower_id 操作ユーザのid followed_id: follow対象のuser_idで特定してdelete

@enduml